### ISSUE TITLE
pip install error on PyPy 7.1.1

### ISSUE THREAD

**Issue by Nitrooo** [antocuni/pypy-wheels#17] opened 2019-07-03 00:17 UTC
$ pip install --no-cache-dir --extra-index https://antocuni.github.io/pypy-wheels/ubuntu numpy
Looking in indexes: https://pypi.org/simple, https://antocuni.github.io/pypy-wheels/ubuntu
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/d3/4b/f9f4b96c0b1ba43d28a5bdc4b64f0b9d3fbcf31313a51bc766942866a7c7/numpy-1.16.4.zip (5.1MB)
     |████████████████████████████████| 5.1MB 3.7MB/s 
Building wheels for collected packages: numpy
  Building wheel for numpy (setup.py) ... error
.
.
.

**Comment by mattip** [comment] 2019-07-03 00:42
What OS? PyPy2 or PyPy3? Can you find the actual error?

**Comment by Nitrooo** [comment] 2019-07-03 01:19
> What OS? PyPy2 or PyPy3? Can you find the actual error?

Linux Mint 19.1, PyPy3.6 v7.1.1.
If I got it right it should install from a precompiled wheel (.whl), but a .zip file from `https://files.pythonhosted.org` is downloaded instead. I cut the error because it is a very long compilation failed message.

**Comment by Nitrooo** [comment] 2019-07-03 12:53
@mattip this is probably caused by #16, but there has been no answer from the owner.
Considering that PyPy 7.1.1 was released in April, I wonder if this repository is abandoned. If so, is there a guide to compile numpy for PyPy?

**Comment by antocuni** [comment] 2019-07-05 14:07
closing because it is a duplicate of #16 . PyPy3 wheels are built now

**Closed by antocuni** 2019-07-05 14:07 UTC
